set_property SRC_FILE_INFO {cfile:/home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc rfile:../../../../../constrs_kc705_timing.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ddr3.xdc rfile:../../../../../constrs_kc705_ddr3.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705.xdc rfile:../../../../../constrs_kc705.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ohio.xdc rfile:../../../../../constrs_kc705_ohio.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/bram_rd53a_quad_ohio/yarr/yarr.runs/synth_1/dont_touch.xdc rfile:../dont_touch.xdc id:5} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins app_0/wb_exp_comp/cfg_interrupt_s_reg/C] -to [get_pins pcie_0/U0/inst/pcie_top_i/pcie_7x_i/pcie_block_i/CFGINTERRUPTN]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT1} ]] -to [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT0} ]] 4.000
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT0} ]] -to [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT1} ]] 6.125
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT0} ]] -to [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT3} ]] 12.250
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT3} ]] -to [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT0} ]] 4.000
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT3} ]] -to [get_clocks -of_objects [get_pins -hier -filter {NAME =~ */CLKOUT1} ]] 6.125
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports pcie_clk_p]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports pcie_clk_n]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA15 [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA16 [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA17 [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y15 [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16 [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD17 [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB18 [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18 [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD18 [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG19 [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK19 [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG18 [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF18 [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH19 [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ19 [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE19 [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD19 [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ17 [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG15 [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15 [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH17 [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH15 [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK15 [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8 [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK6 [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG7 [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7 [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK4 [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ8 [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6 [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH5 [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6 [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ2 [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2 [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4 [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ4 [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK1 [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ1 [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1 [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2 [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE4 [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3 [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3 [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1 [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD3 [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4 [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC5 [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE6 [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6 [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2 [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:2 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4 [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:2 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ11 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:2 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:2 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK14 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:2 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:2 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ13 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ12 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG12 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG13 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK9 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:2 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:2 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9 [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:2 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:2 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11 [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_we_n]
set_property src_info {type:XDC file:2 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property src_info {type:XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE9 [get_ports ddr3_we_n]
set_property src_info {type:XDC file:2 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK3 [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD8 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:2 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:2 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC12 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:2 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:2 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:2 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:2 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:2 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:2 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:2 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:2 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE16 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:2 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:2 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:2 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK5 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:2 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:2 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:2 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ3 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:2 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:2 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:2 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF6 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:2 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:2 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:2 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC15 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC16 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:2 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:2 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:2 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:2 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK18 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:2 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:2 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:2 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:2 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:2 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ16 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:2 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH16 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:2 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:2 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:2 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ7 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:2 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:2 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:2 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:2 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG2 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:2 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:2 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:2 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:2 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG3 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:2 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG4 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:2 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:2 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:2 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:2 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:2 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:2 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:2 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:2 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH10 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports clk200_p]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports clk200_n]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports sys_rst_n_i]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {pci_exp_rxp[0]}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M5 [get_ports {pci_exp_rxn[0]}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports {pci_exp_rxp[1]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {pci_exp_rxn[1]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports {pci_exp_rxp[2]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {pci_exp_rxn[2]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {pci_exp_rxp[3]}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {pci_exp_rxn[3]}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports rst_n_i]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y29 [get_ports {usr_sw_i[0]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W29 [get_ports {usr_sw_i[1]}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA28 [get_ports {usr_sw_i[2]}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {usr_led_o[0]}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {usr_led_o[1]}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {usr_led_o[2]}]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD29 [get_ports {fe_data_p[0]}]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE29 [get_ports {fe_data_n[0]}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y30  [get_ports {fe_data_p[1]}]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA30 [get_ports {fe_data_n[1]}]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB29 [get_ports {fe_data_p[2]}]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB30 [get_ports {fe_data_n[2]}]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE30 [get_ports {fe_data_p[3]}]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF30 [get_ports {fe_data_n[3]}]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC29 [get_ports {fe_cmd_p[0]}]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC30 [get_ports {fe_cmd_n[0]}]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG27 [get_ports {fe_data_p[4]}]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG28 [get_ports {fe_data_n[4]}]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE28 [get_ports {fe_data_p[5]}]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF28 [get_ports {fe_data_n[5]}]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC26 [get_ports {fe_data_p[6]}]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD26 [get_ports {fe_data_n[6]}]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ27 [get_ports {fe_data_p[7]}]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK28 [get_ports {fe_data_n[7]}]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG30 [get_ports {fe_cmd_p[1]}]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH30 [get_ports {fe_cmd_n[1]}]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {fe_data_p[8]}]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {fe_data_n[8]}]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24 [get_ports {fe_data_p[9]}]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD24 [get_ports {fe_data_n[9]}]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports {fe_data_p[10]}]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF25 [get_ports {fe_data_n[10]}]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG25 [get_ports {fe_data_p[11]}]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH25 [get_ports {fe_data_n[11]}]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC22 [get_ports {fe_cmd_p[2]}]
set_property src_info {type:XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD22 [get_ports {fe_cmd_n[2]}]
set_property src_info {type:XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20 [get_ports {fe_data_p[12]}]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF21 [get_ports {fe_data_n[12]}]
set_property src_info {type:XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ22 [get_ports {fe_data_p[13]}]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ23 [get_ports {fe_data_n[13]}]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG20 [get_ports {fe_data_p[14]}]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH20 [get_ports {fe_data_n[14]}]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD23 [get_ports {fe_data_p[15]}]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE24 [get_ports {fe_data_n[15]}]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH21 [get_ports {fe_cmd_p[3]}]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports {fe_cmd_n[3]}]
set_property src_info {type:XDC file:4 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF26 [get_ports {fe_clk_p[0]}]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF27 [get_ports {fe_clk_n[0]}]
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH26 [get_ports {fe_clk_p[1]}]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH27 [get_ports {fe_clk_n[1]}]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK29 [get_ports {fe_clk_p[2]}]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK30 [get_ports {fe_clk_n[2]}]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28 [get_ports {fe_clk_p[3]}]
set_property src_info {type:XDC file:4 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29 [get_ports {fe_clk_n[3]}]
set_property src_info {type:XDC file:4 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG22 [get_ports {latch_o}]
set_property src_info {type:XDC file:4 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH22 [get_ports {sdi_i}]
set_property src_info {type:XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24 [get_ports {sda_o}]
set_property src_info {type:XDC file:4 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC25 [get_ports {scl_o}]
set_property src_info {type:XDC file:4 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB27 [get_ports {sda_io}]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC27 [get_ports {scl_io}]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {sda_io}]
set_property src_info {type:XDC file:4 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {scl_io}]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE23 [get_ports {ext_trig_i_p[0]}]
set_property src_info {type:XDC file:4 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF23 [get_ports {ext_trig_i_n[0]}]
set_property src_info {type:XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {ext_trig_i_p[1]}]
set_property src_info {type:XDC file:4 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK21 [get_ports {ext_trig_i_n[1]}]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK23 [get_ports {ext_trig_i_p[2]}]
set_property src_info {type:XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK24 [get_ports {ext_trig_i_n[2]}]
set_property src_info {type:XDC file:4 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24 [get_ports {ext_trig_i_p[3]}]
set_property src_info {type:XDC file:4 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25 [get_ports {ext_trig_i_n[3]}]
set_property src_info {type:XDC file:4 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD21 [get_ports {eudet_trig_p}]
set_property src_info {type:XDC file:4 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE21 [get_ports {eudet_trig_n}]
set_property src_info {type:XDC file:4 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD27 [get_ports {eudet_busy_p}]
set_property src_info {type:XDC file:4 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD28 [get_ports {eudet_busy_n}]
set_property src_info {type:XDC file:4 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ26 [get_ports {eudet_clk_p}]
set_property src_info {type:XDC file:4 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK26 [get_ports {eudet_clk_n}]
set_property src_info {type:XDC file:4 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_160_s -max [expr 6.25 - 0.050] [get_ports fe_cmd_*];
set_property src_info {type:XDC file:4 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_160_s -min -0.050                        [get_ports fe_cmd_*];
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]
