# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/kc705-fmc-quad-dp-ohio-dbyarr-dataC.xdc

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_32x512/fifo_32x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32x512 || ORIG_REF_NAME==fifo_32x512}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_rx_dma_wb || ORIG_REF_NAME==ila_rx_dma_wb}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l2p_fifo64 || ORIG_REF_NAME==l2p_fifo64}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_64x512 || ORIG_REF_NAME==fifo_64x512}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_96x512 || ORIG_REF_NAME==fifo_96x512}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_256x16 || ORIG_REF_NAME==fifo_256x16}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_channel_fifo || ORIG_REF_NAME==rx_channel_fifo}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_29x32 || ORIG_REF_NAME==fifo_29x32}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_8x32 || ORIG_REF_NAME==fifo_8x32}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_fifo || ORIG_REF_NAME==tx_fifo}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_605x32 || ORIG_REF_NAME==fifo_605x32}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_bridge_ctrl_fifo || ORIG_REF_NAME==rx_bridge_ctrl_fifo}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_bridge_fifo || ORIG_REF_NAME==rx_bridge_fifo}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_ddr/ila_ddr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_ddr || ORIG_REF_NAME==ila_ddr}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_axis/ila_axis.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_axis || ORIG_REF_NAME==ila_axis}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_wsh_pipe/ila_wsh_pipe.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_wsh_pipe || ORIG_REF_NAME==ila_wsh_pipe}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_gen || ORIG_REF_NAME==clk_gen}]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}]
