# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.xci
# IP: The module: 'ila_rx_dma_wb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rx_dma_wb'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rx_dma_wb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.xci
# IP: The module: 'ila_rx_dma_wb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rx_dma_wb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rx_dma_wb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
