# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci
# IP: The module: 'tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo/tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo/tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci
# IP: The module: 'tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo/tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo/tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
