# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/kc705-fmc-quad-dp-ohio-dbyarr.xdc

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]
