# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/bram_rd53a_quad_ohio/yarr/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/bram_rd53a_quad_ohio/yarr/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.3 [current_project]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_axis/ila_axis.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_axis/ila_axis.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_ddr/ila_ddr.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_ddr/ila_ddr.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_32x512/fifo_32x512.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_32x512/fifo_32x512.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_wsh_pipe/ila_wsh_pipe.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_wsh_pipe/ila_wsh_pipe.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.dcp]
add_files -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.dcp
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.dcp]
read_mem /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/dec.mif
read_ip -quiet /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_7series_0.xci
set_property is_locked true [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_7series_0.xci]

read_verilog -library xil_defaultlib /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/descrambler.v
read_vhdl -library xil_defaultlib {
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/xapp1017/delay_controller_wrap.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/xapp1017/serdes_1_to_468_idelay_ddr.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/gearbox32to66.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/cdr_serdes.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/bram_rd53a_quad_ohio/board_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/l2p_fifo.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/data_alignment.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/aurora_rx_lane.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/synchronizer.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/rr_arbiter.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/generic_async_fifo_wrapper.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/common_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/tx-core/serial_port.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/trigger-logic/eudet_tlu.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/trigger-logic/edge_detector.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/trigger-logic/delayer.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/wbmaster32.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/p2l_dma_master.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/p2l_decoder.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/l2p_dma_master.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/l2p_arbiter.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/fei4_rx_channel.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/aurora_rx_channel.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/tx-core/tx_channel.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/tx-core/trigger_unit.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/i2c-master/i2c_master_registers.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/i2c-master/i2c_master_byte_ctrl.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/i2c-master/i2c_master_bit_ctrl.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/trigger-logic/wb_trigger_logic.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/wb_rx_core.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/rx-core/wb_rx_bridge.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/wb_spi.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/wb_addr_decoder.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/simple_counter.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/common/k_dual_bram.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/tx-core/wb_tx_core.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/rtl/i2c-master/i2c_master_wb_top.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/xpressk7/app_pkg.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/xpressk7/app.vhd
  /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/bram_yarr_kc705.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705.xdc
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705.xdc]

read_xdc /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc]

read_xdc /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/kc705-fmc-quad-dp-ohio-dbyarr.xdc
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/kc705-fmc-quad-dp-ohio-dbyarr.xdc]

read_xdc /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc
set_property used_in_implementation false [get_files /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_level -part xc7k325tffg900-2


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
