# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci
# IP: The module: 'axis_data_fifo_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1/axis_data_fifo_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1/axis_data_fifo_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci
# IP: The module: 'axis_data_fifo_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1/axis_data_fifo_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/atlasj/work/XpressK7_RD53A/YARR_ocha/debug/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1/axis_data_fifo_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
